image: archlinux
packages:
  - hut
  - pixi
  - just
  - rattler-build

secrets:
  - 49004ca8-1e5d-4c1f-a3fe-9c34c7f41fea

oauth: pages.sr.ht/PAGES:RW
environment:
  site: cheetah.farthergate.com
  CONDA_BUILD_WINSDK: /home/build/winsdk

sources:
  - https://git.sr.ht/~aleksrutins/cheetah
  - https://git.sr.ht/~aleksrutins/cicada

tasks:
  - winsdk: |
      mkdir $CONDA_BUILD_WINSDK
  # TODO: macOS builds broken for the moment
  - publish-package: |
      cd cheetah
      just build-and-publish
  - build-docs: |
      cd cheetah/docs
      pixi i
      pixi run build
  - package-docs: |
      cd cheetah/docs/_build/pages
      tar -cvz . > ../../../../site.tar.gz
  - upload-docs: |
      hut pages publish -d $site site.tar.gz
