image: archlinux
packages:
  - hut
  - pixi
  - just

secrets:
  - 45a77966-954e-422e-b388-56e1d0d54ffb

oauth: pages.sr.ht/PAGES:RW
environment:
  site: cheetah.farthergate.com
  CONDA_BUILD_WINSDK: /home/build/winsdk

sources:
  - https://git.sr.ht/~aleksrutins/cheetah
  - https://git.sr.ht/~aleksrutins/cicada

tasks:
  - winsdk: |
      mkdir $CONDA_BUILD_WINSDK
  # TODO: macOS builds broken for the moment
  - publish-package: |
      cd cheetah
      just build-and-publish
  - build-docs: |
      cd cheetah/docs
      pixi i
      pixi run build
  - package-docs: |
      cd cheetah/docs/_build/pages
      tar -cvz . > ../../../../site.tar.gz
  - upload-docs: |
      hut pages publish -d $site site.tar.gz
