image: nixos/unstable
packages:
  - nixpkgs.hut
  - nixpkgs.pixi

repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable

oauth: pages.sr.ht/PAGES:RW
environment:
  site: cheetah.farthergate.com
tasks:
  - build: |
      cd cheetah/docs
      pixi i
      pixi run build
  - package: |
      cd cheetah/docs/_build
      tar -cvz . > ../../../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
