image: alpine/edge
packages:
  - curl
  - hut
oauth: pages.sr.ht/PAGES:RW
environment:
  site: cheetah.farthergate.com
tasks:
  - pixi: |
      curl -fsSL https://pixi.sh/install.sh | sh
  - build: |
      cd cheetah/docs
      pixi run build
  - package: |
      cd cheetah/docs/_build
      tar -cvz . > ../../../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
