[package]
name = "hyena"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.11"
html_parser = "0.6.3"
pulldown-cmark = "0.9.1"
regex = "1.6.0"
