context:
  version: 0.2.3
  name: cheetah

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ..

build:
  script:
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml # !(1)
    - $BUILD_PREFIX/bin/cargo install --locked --bins --root ${PREFIX} --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses

tests:
  - script:
      - cargo test

about:
  homepage: https://cheetah.farthergate.com
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: "A fast static site generator."
  summary: "A fast static site generator."
