name: "Build with Nix"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: cachix/cachix-action@v13
        with:
          name: aleksrutins
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build package
        run: nix build
