name: Publish

on:
  push:
    tags: "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo fmt && cargo clippy
    - name: Publish
      run: cargo publish --token=${{ secrets.CARGO_TOKEN }}
